--
--  Copyright (C) 2024-2025, Vadim Godunko <vgodunko@gmail.com>
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

--  Fill '.bss' section by zeros.
--
--  It uses external symbols generated by the linker:
--   - _sbss
--   - _ebss

procedure A0B.ARMv7M.Startup_Utilities.Fill_BSS_Section
  with Preelaborate, No_Elaboration_Code_All, Inline_Always;
