--
--  Copyright (C) 2024-2025, Vadim Godunko <vgodunko@gmail.com>
--
--  SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
--

--  Copy '.itcm.text' from the flash to the ITCM RAM region.
--
--  It uses external symbols generated by the linker:
--   - _siitcmtext
--   - _sitcmtext
--   - _eitcmtext

procedure A0B.ARMv7M.Startup_Utilities.Copy_ITCM_Text_Section
  with Preelaborate, No_Elaboration_Code_All, Inline_Always;
